spring.application.name=med-voll-api
# =======================================================
# CONFIGURACAO DE CONEXAO COM O BANCO DE DADOS (MySQL)
# =======================================================
spring.datasource.url=jdbc:mysql://localhost/med_voll_api_db
spring.datasource.username=lucas_the_st8ic_user_admin
spring.datasource.password=Lss@Ann120677100698
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================================================
# CONFIGURACAO DO JPA / HIBERNATE
# =======================================================
# 'none' ou 'validate' é o recomendado ao usar Flyway (deixa o controle de DDL com o Flyway)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.web.error.include-stacktrace=never

# =======================================================
# CONFIGURACAO DO FLYWAY MIGRATION
# =======================================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.security.user.name=